apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1-dp
  labels:
    app: nginx
    server: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      server: webserver
  template:
    metadata:
      labels:
       app: nginx
       server: webserver
    spec:
      containers:
      - name: nginx1
        image: nginx 1.7.9
        ports:
        - containerPort: 80
