apiVersion: v1
kind: Service
metadata:
 name: kubernetes-dashboard-svc
 labels:
   k8s-app: kubernetes-dashboard
spec:
 type: NodePort
 ports:
   - port: 9090
     targetPort: 9090
     nodePort: 31567
     protocol: TCP
 selector:
   k8s-app: kubernetes-dashboard
