apiVersion: v1
kind: Pod
metadata:
  name: busybox1-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybobx1
    image: busybox:latest
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-c", "env"]
    env:
      - name: MY_VALUE1
        valueFrom:
          configMapKeyRef:
            name: configmap1
            key: name
      - name: MY_VALUE2
        valueFrom:
          configMapKeyRef:
            name: configmap1
            key: school
  restartPolicy: Never
